on: 
  push:
    branches: [ docker ]
    tags:
      - v*
  pull_request:
    branches: [ docker ]
name: Build
jobs:
  buildx:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          driver-opts: |
            network=bridge
          buildkitd-flags: --allow-insecure-entitlement security.insecure
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Show the env
        id: show
        env:
          QEMU_LD_PREFIX: /usr/arm-linux-gnueabihf
        run: |
          uname -a
      - name: Build and Push
        uses: docker/build-push-action@v2
        id: build
        with:
          context: .
          push: true
          tags: |
            ${{ env.GITHUB_REPOSITORY }}:latest
      -
        name: Inspect image
        if: always() && github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.GITHUB_REPOSITORY }}@${{ steps.build.outputs.digest }}
